// apps/react-demo/src/App.tsx
/**
 * Since this file is for development purposes only, some of the dependencies are in devDependencies
 * Disabling ESLint rules for these dependencies since we know it is only for development purposes
 */

import React, { useCallback, useEffect, useState, useRef } from 'react';
// eslint-disable-next-line import/no-extraneous-dependencies
import ReactDOMClient from 'react-dom/client';
// eslint-disable-next-line import/no-extraneous-dependencies
import styled, { createGlobalStyle } from 'styled-components';
import { shuffle } from 'lodash-es';

import {
  useFocusable,
  init,
  FocusContext,
  FocusDetails,
  FocusableComponentLayout,
  KeyPressDetails
} from '@noriginmedia/norigin-spatial-navigation';

import logo from './logo.png';

init({
  debug: false,
  visualDebug: false,
  distanceCalculationMethod: 'center',
  onUtterText: (text: string) => {
    // eslint-disable-next-line no-console
    console.log('onUtterText', text);
  }
});

const rows = shuffle([
  {
    title: 'Recommended'
  },
  {
    title: 'Movies'
  },
  {
    title: 'Series'
  },
  {
    title: 'TV Channels'
  },
  {
    title: 'Sport'
  }
]);

const assets = [
  {
    title: 'Asset 1',
    color: '#714ADD'
  },
  {
    title: 'Asset 2',
    color: '#AB8DFF'
  },
  {
    title: 'Asset 3',
    color: '#512EB0'
  },
  {
    title: 'Asset 4',
    color: '#714ADD'
  },
  {
    title: 'Asset 5',
    color: '#AB8DFF'
  },
  {
    title: 'Asset 6',
    color: '#512EB0'
  },
  {
    title: 'Asset 7',
    color: '#714ADD'
  },
  {
    title: 'Asset 8',
    color: '#AB8DFF'
  },
  {
    title: 'Asset 9',
    color: '#512EB0'
  }
];

interface MenuItemBoxProps {
  focused: boolean;
}

const MenuItemBox = styled.div<MenuItemBoxProps>`
  width: 171px;
  height: 51px;
  background-color: #b056ed;
  border-color: white;
  border-style: solid;
  border-width: ${({ focused }) => (focused ? '6px' : 0)};
  box-sizing: border-box;
  border-radius: 7px;
  margin-bottom: 37px;
`;

function MenuItem() {
  const { ref, focused } = useFocusable<object, HTMLDivElement>();

  return <MenuItemBox ref={ref} focused={focused} />;
}

interface MenuWrapperProps {
  hasFocusedChild: boolean;
}

const MenuWrapper = styled.div<MenuWrapperProps>`
  flex: 1;
  max-width: 246px;
  display: flex;
  flex-direction: column;
  align-items: center;
  background-color: ${({ hasFocusedChild }) =>
    hasFocusedChild ? '#4e4181' : '#362C56'};
  padding-top: 37px;
`;

const NmLogo = styled.img`
  height: 57px;
  width: 175px;
  margin-bottom: 51px;
`;

interface MenuProps {
  focusKey: string;
}

function Menu({ focusKey: focusKeyParam }: MenuProps) {
  const {
    ref,
    focusSelf,
    hasFocusedChild,
    focusKey
    // setFocus, -- to set focus manually to some focusKey
    // navigateByDirection, -- to manually navigate by direction
    // pause, -- to pause all navigation events
    // resume, -- to resume all navigation events
    // updateAllLayouts, -- to force update all layouts when needed
    // getCurrentFocusKey -- to get the current focus key
  } = useFocusable<object, HTMLDivElement>({
    focusable: true,
    saveLastFocusedChild: false,
    trackChildren: true,
    autoRestoreFocus: true,
    isFocusBoundary: false,
    focusKey: focusKeyParam,
    preferredChildFocusKey: null,
    onEnterPress: () => {},
    onEnterRelease: () => {},
    onArrowPress: () => true,
    onArrowRelease: () => {},
    onFocus: () => {},
    onBlur: () => {},
    extraProps: { foo: 'bar' }
  });

  useEffect(() => {
    focusSelf();
  }, [focusSelf]);

  return (
    <FocusContext.Provider value={focusKey}>
      <MenuWrapper ref={ref} hasFocusedChild={hasFocusedChild}>
        <NmLogo src={logo} />
        <MenuItem />
        <MenuItem />
        <MenuItem />
        <MenuItem />
        <MenuItem />
      </MenuWrapper>
    </FocusContext.Provider>
  );
}

const AssetWrapper = styled.div`
  margin-right: 22px;
  display: flex;
  flex-direction: column;
`;

interface AssetBoxProps {
  index: number;
  isShuffleSize: boolean;
  focused: boolean;
  color: string;
}

const AssetBox = styled.div<AssetBoxProps>`
  width: ${({ isShuffleSize, index }) =>
    isShuffleSize ? `${80 + index * 30}px` : '225px'};
  height: 127px;
  background-color: ${({ color }) => color};
  border-color: white;
  border-style: solid;
  border-width: ${({ focused }) => (focused ? '6px' : 0)};
  box-sizing: border-box;
  border-radius: 7px;
`;

const AssetTitle = styled.div`
  color: white;
  margin-top: 10px;
  font-family: 'Segoe UI';
  font-size: 24px;
  font-weight: 400;
`;

interface AssetProps {
  index: number;
  isShuffleSize: boolean;
  title: string;
  color: string;
  onEnterPress: (props: object, details: KeyPressDetails) => void;
  onFocus: (
    layout: FocusableComponentLayout,
    props: object,
    details: FocusDetails
  ) => void;
}

function Asset({
  title,
  color,
  onEnterPress,
  onFocus,
  isShuffleSize,
  index
}: AssetProps) {
  const { ref, focused } = useFocusable<object, HTMLDivElement>({
    accessibilityLabel: title,
    onEnterPress,
    onFocus,
    extraProps: {
      title,
      color
    }
  });

  return (
    <AssetWrapper ref={ref}>
      <AssetBox
        index={index}
        color={color}
        focused={focused}
        isShuffleSize={isShuffleSize}
      />
      <AssetTitle>{title}</AssetTitle>
    </AssetWrapper>
  );
}

const ContentRowWrapper = styled.div`
  margin-bottom: 37px;
`;

const ContentRowTitle = styled.div`
  color: white;
  margin-bottom: 22px;
  font-size: 27px;
  font-weight: 700;
  font-family: 'Segoe UI';
  padding-left: 60px;
`;

const ContentRowScrollingWrapper = styled.div`
  overflow-x: auto;
  overflow-y: hidden;
  flex-shrink: 1;
  flex-grow: 1;
  padding-left: 60px;
`;

const ContentRowScrollingContent = styled.div`
  display: flex;
  flex-direction: row;
`;

interface ContentRowProps {
  isShuffleSize: boolean;
  title: string;
  onAssetPress: (props: object, details: KeyPressDetails) => void;
  onFocus: (
    layout: FocusableComponentLayout,
    props: object,
    details: FocusDetails
  ) => void;
}

function ContentRow({
  title: rowTitle,
  onAssetPress,
  onFocus,
  isShuffleSize
}: ContentRowProps) {
  const { ref, focusKey } = useFocusable<object, HTMLDivElement>({
    accessibilityLabel: rowTitle,
    onFocus
  });

  const scrollingRef = useRef(null);

  const onAssetFocus = useCallback(
    ({ x }: { x: number }) => {
      scrollingRef.current.scrollTo({
        left: x,
        behavior: 'smooth'
      });
    },
    [scrollingRef]
  );

  return (
    <FocusContext.Provider value={focusKey}>
      <ContentRowWrapper ref={ref}>
        <ContentRowTitle>{rowTitle}</ContentRowTitle>
        <ContentRowScrollingWrapper ref={scrollingRef}>
          <ContentRowScrollingContent>
            {assets.map(({ title, color }, index) => (
              <Asset
                index={index}
                title={title}
                key={title}
                color={color}
                onEnterPress={onAssetPress}
                onFocus={onAssetFocus}
                isShuffleSize={isShuffleSize}
              />
            ))}
          </ContentRowScrollingContent>
        </ContentRowScrollingWrapper>
      </ContentRowWrapper>
    </FocusContext.Provider>
  );
}

const ContentWrapper = styled.div`
  flex: 1;
  overflow: hidden;
  display: flex;
  flex-direction: column;
`;

const ContentTitle = styled.div`
  color: white;
  font-size: 48px;
  font-weight: 600;
  font-family: 'Segoe UI';
  text-align: center;
  margin-top: 52px;
  margin-bottom: 37px;
`;

const SelectedItemWrapper = styled.div`
  position: relative;
  display: flex;
  flex-direction: column;
  align-items: center;
`;

const SelectedItemBox = styled.div`
  height: 282px;
  width: 1074px;
  background-color: ${({ color }) => color};
  margin-bottom: 37px;
  border-radius: 7px;
`;

const SelectedItemTitle = styled.div`
  position: absolute;
  bottom: 75px;
  left: 100px;
  color: white;
  font-size: 27px;
  font-weight: 400;
  font-family: 'Segoe UI';
`;

const ScrollingRows = styled.div`
  overflow-y: auto;
  overflow-x: hidden;
  flex-shrink: 1;
  flex-grow: 1;
`;

interface ProgressBarWrapperProps {
  focused: boolean;
}

interface ProgressBarProgressProps {
  percent: number;
  focused: boolean;
}

const ProgressBarWrapper = styled.div<ProgressBarWrapperProps>`
  position: absolute;
  bottom: 95px;
  right: 100px;
  width: 540px;
  height: 24px;
  background-color: gray;
  border-radius: 21px;
  border-color: white;
  border-style: solid;
  border-width: ${({ focused }) => (focused ? '6px' : 0)};
  box-sizing: border-box;
`;

const ProgressBarProgress = styled.div<ProgressBarProgressProps>`
  width: ${({ percent }) => `${percent}%`};
  height: 100%;
  background-color: ${({ focused }) =>
    focused ? 'deepskyblue' : 'dodgerblue'};
  border-radius: 21px;
`;

const defaultPercent = 10;
const seekPercent = 10;
const delayedTime = 100;
const DIRECTION_RIGHT = 'right';

function ProgressBar() {
  const [percent, setPercent] = useState(defaultPercent);
  const timerRef = useRef<NodeJS.Timeout | null>(null);
  const { ref, focused } = useFocusable<object, HTMLDivElement>({
    onArrowPress: (direction: string) => {
      if (direction === DIRECTION_RIGHT && timerRef.current === null) {
        timerRef.current = setInterval(() => {
          setPercent((prevPercent) =>
            prevPercent >= 100 ? prevPercent : prevPercent + seekPercent
          );
        }, delayedTime);
        return true;
      }
      return true;
    },
    onArrowRelease: (direction: string) => {
      if (direction === DIRECTION_RIGHT) {
        clearInterval(timerRef.current);
        timerRef.current = null;
      }
    }
  });
  useEffect(() => {
    if (!focused) {
      setPercent(defaultPercent);
    }
  }, [focused]);
  useEffect(
    () => () => {
      if (timerRef.current !== null) {
        clearInterval(timerRef.current);
        timerRef.current = null;
      }
    },
    []
  );
  return (
    <ProgressBarWrapper ref={ref} focused={focused}>
      <ProgressBarProgress percent={percent} focused={focused} />
    </ProgressBarWrapper>
  );
}

function Content() {
  const { ref, focusKey } = useFocusable<object, HTMLDivElement>();

  const [selectedAsset, setSelectedAsset] = useState(null);

  const onAssetPress = useCallback((asset: AssetProps) => {
    setSelectedAsset(asset);
  }, []);

  const onRowFocus = useCallback(
    ({ y }: { y: number }) => {
      ref.current.scrollTo({
        top: y,
        behavior: 'smooth'
      });
    },
    [ref]
  );

  return (
    <FocusContext.Provider value={focusKey}>
      <ContentWrapper>
        <ContentTitle>Norigin Spatial Navigation</ContentTitle>
        <SelectedItemWrapper>
          <SelectedItemBox
            color={selectedAsset ? selectedAsset.color : '#565b6b'}
          />
          <SelectedItemTitle>
            {selectedAsset
              ? selectedAsset.title
              : 'Press "Enter" to select an asset'}
          </SelectedItemTitle>
          <ProgressBar />
        </SelectedItemWrapper>
        <ScrollingRows ref={ref}>
          <div>
            {rows.map(({ title }) => (
              <ContentRow
                key={title}
                title={title}
                onAssetPress={onAssetPress}
                onFocus={onRowFocus}
                isShuffleSize={Math.random() < 0.5} // Rows will have children assets of different sizes, randomly setting it to true or false.
              />
            ))}
          </div>
        </ScrollingRows>
      </ContentWrapper>
    </FocusContext.Provider>
  );
}

const AppContainer = styled.div`
  background-color: #221c35;
  width: 1440px;
  height: 810px;
  display: flex;
  flex-direction: row;
`;

const GlobalStyle = createGlobalStyle`
  ::-webkit-scrollbar {
    display: none;
  }
`;

function App() {
  return (
    <React.StrictMode>
      <AppContainer>
        <GlobalStyle />
        <Menu focusKey="MENU" />
        <Content />
      </AppContainer>
    </React.StrictMode>
  );
}

const root = ReactDOMClient.createRoot(document.querySelector('#root'));
root.render(<App />);

// apps/svelte-demo/src/App.svelte
<script lang="ts">
  import { onDestroy } from 'svelte';
  import { mount } from 'svelte';
  import { shuffle } from 'lodash-es';
  import {
    SpatialRoot,
    SpatialNode,
    Focusable,
    setFocus,
    type FocusableComponentLayout,
    type FocusDetails,
    type KeyPressDetails
  } from '@noriginmedia/norigin-spatial-navigation-svelte';

  // ─── Data ────────────────────────────────────────────────────

  const rows = shuffle([
    { title: 'Recommended' },
    { title: 'Movies' },
    { title: 'Series' },
    { title: 'TV Channels' },
    { title: 'Sport' }
  ]);

  const assets = [
    { title: 'Asset 1', color: '#714ADD' },
    { title: 'Asset 2', color: '#AB8DFF' },
    { title: 'Asset 3', color: '#512EB0' },
    { title: 'Asset 4', color: '#714ADD' },
    { title: 'Asset 5', color: '#AB8DFF' },
    { title: 'Asset 6', color: '#512EB0' },
    { title: 'Asset 7', color: '#714ADD' },
    { title: 'Asset 8', color: '#AB8DFF' },
    { title: 'Asset 9', color: '#512EB0' }
  ];

  // ─── Content State ───────────────────────────────────────────

  let selectedAsset: { title: string; color: string } | null = $state(null);
  let scrollingRowsEl: HTMLDivElement;

  function onAssetPress(props: { title: string; color: string }, _details: KeyPressDetails) {
    selectedAsset = props;
  }

  function onRowFocus(layout: FocusableComponentLayout, _props: any, _details: FocusDetails) {
    scrollingRowsEl?.scrollTo({ top: layout.y, behavior: 'smooth' });
  }

  // ─── Progress Bar State ──────────────────────────────────────

  const DEFAULT_PERCENT = 10;
  const SEEK_PERCENT = 10;
  const DELAY_MS = 100;

  let percent = $state(DEFAULT_PERCENT);
  let progressFocused = $state(false);
  let timer: ReturnType<typeof setInterval> | null = null;

  $effect(() => {
    if (!progressFocused) {
      percent = DEFAULT_PERCENT;
    }
  });

  onDestroy(() => {
    if (timer !== null) {
      clearInterval(timer);
      timer = null;
    }
  });

  function handleArrowPress(direction: string): boolean {
    if (direction === 'right' && timer === null) {
      timer = setInterval(() => {
        percent = Math.min(100, percent + SEEK_PERCENT);
      }, DELAY_MS);
    }
    return true;
  }

  function handleArrowRelease(direction: string): void {
    if (direction === 'right' && timer !== null) {
      clearInterval(timer);
      timer = null;
    }
  }
</script>

<SpatialRoot
  debug={false}
  visualDebug={false}
  distanceCalculationMethod="center"
  initialFocusKey="MENU"
  onUtterText={(text) => console.log('onUtterText', text)}
>
  <div class="app-container">

    <!-- ─── Menu ──────────────────────────────────────────────── -->
    <SpatialNode navKey="MENU" saveLastFocusedChild={false} trackChildren forceFocus>
      {#snippet children({ hasFocusedChild, spatial })}
        <div use:spatial class="menu" class:has-focused-child={hasFocusedChild}>
          <div class="logo-placeholder">NM</div>
          {#each Array(5) as _}
            <SpatialNode>
              {#snippet children({ focused, spatial: itemSpatial })}
                <div use:itemSpatial class="menu-item" class:focused></div>
              {/snippet}
            </SpatialNode>
          {/each}
        </div>
      {/snippet}
    </SpatialNode>

    <!-- ─── Content ───────────────────────────────────────────── -->
    <SpatialNode navKey="CONTENT">
      {#snippet children({ spatial })}
        <div use:spatial class="content-wrapper">
          <div class="content-title">Norigin Spatial Navigation</div>

          <div class="selected-item-wrapper">
            <div
              class="selected-item-box"
              style:background-color={selectedAsset?.color ?? '#565b6b'}
            ></div>
            <div class="selected-item-title">
              {selectedAsset?.title ?? 'Press "Enter" to select an asset'}
            </div>

            <!-- Progress Bar -->
            <SpatialNode
              bind:focused={progressFocused}
              onArrowPress={handleArrowPress}
              onArrowRelease={handleArrowRelease}
            >
              {#snippet children({ focused: pFocused, spatial: pSpatial })}
                <div use:pSpatial class="progress-wrapper" class:focused={pFocused}>
                  <div class="progress-bar" class:focused={pFocused} style:width="{percent}%"></div>
                </div>
              {/snippet}
            </SpatialNode>
          </div>

          <div class="scrolling-rows" bind:this={scrollingRowsEl}>
            <div>
              {#each rows as row (row.title)}
                {@const isShuffleSize = Math.random() < 0.5}
                <SpatialNode navKey={`row-${row.title}`} accessibilityLabel={row.title} onFocus={onRowFocus}>
                  {#snippet children({ spatial: rowSpatial })}
                    {@const scrollingEl = { current: null as HTMLDivElement | null }}
                    <div use:rowSpatial class="content-row">
                      <div class="row-title">{row.title}</div>
                      <div class="scrolling-wrapper" bind:this={scrollingEl.current}>
                        <div class="scrolling-content">
                          {#each assets as asset, index (asset.title)}
                            <SpatialNode
                              accessibilityLabel={asset.title}
                              onEnterPress={onAssetPress}
                              extraProps={{ title: asset.title, color: asset.color }}
                              onFocus={(layout) => { scrollingEl.current?.scrollTo({ left: layout.x, behavior: 'smooth' }); }}
                            >
                              {#snippet children({ focused: aFocused, spatial: aSpatial })}
                                <div use:aSpatial class="asset-wrapper">
                                  <div
                                    class="asset-box"
                                    class:focused={aFocused}
                                    style:width={isShuffleSize ? `${80 + index * 30}px` : '225px'}
                                    style:background-color={asset.color}
                                  ></div>
                                  <div class="asset-title">{asset.title}</div>
                                </div>
                              {/snippet}
                            </SpatialNode>
                          {/each}
                        </div>
                      </div>
                    </div>
                  {/snippet}
                </SpatialNode>
              {/each}
            </div>
          </div>
        </div>
      {/snippet}
    </SpatialNode>

  </div>
</SpatialRoot>

<style>
  :global(html, body, div, span, applet, object, iframe,
  h1, h2, h3, h4, h5, h6, p, blockquote, pre,
  a, abbr, acronym, address, big, cite, code,
  del, dfn, em, img, ins, kbd, q, s, samp,
  small, strike, strong, sub, sup, tt, var,
  b, u, i, center, dl, dt, dd, ol, ul, li,
  fieldset, form, label, legend, table, caption,
  tbody, tfoot, thead, tr, th, td, article, aside,
  canvas, details, embed, figure, figcaption,
  footer, header, hgroup, menu, nav, output,
  ruby, section, summary, time, mark, audio, video) {
    margin: 0;
    padding: 0;
    border: 0;
  }

  :global(::-webkit-scrollbar) {
    display: none;
  }

  .app-container {
    background-color: #221c35;
    width: 1440px;
    height: 810px;
    display: flex;
    flex-direction: row;
  }

  /* ─── Menu ─────────────────────────────────────────────── */

  .menu {
    flex: 1;
    max-width: 246px;
    display: flex;
    flex-direction: column;
    align-items: center;
    background-color: #362c56;
    padding-top: 37px;
  }

  .menu.has-focused-child {
    background-color: #4e4181;
  }

  .logo-placeholder {
    height: 57px;
    width: 175px;
    margin-bottom: 51px;
    display: flex;
    align-items: center;
    justify-content: center;
    color: white;
    font-size: 32px;
    font-weight: bold;
    font-family: 'Segoe UI', sans-serif;
  }

  .menu-item {
    width: 171px;
    height: 51px;
    background-color: #b056ed;
    border: 0 solid white;
    box-sizing: border-box;
    border-radius: 7px;
    margin-bottom: 37px;
  }

  .menu-item.focused {
    border-width: 6px;
  }

  /* ─── Content ──────────────────────────────────────────── */

  .content-wrapper {
    flex: 1;
    overflow: hidden;
    display: flex;
    flex-direction: column;
  }

  .content-title {
    color: white;
    font-size: 48px;
    font-weight: 600;
    font-family: 'Segoe UI', sans-serif;
    text-align: center;
    margin-top: 52px;
    margin-bottom: 37px;
  }

  .selected-item-wrapper {
    position: relative;
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .selected-item-box {
    height: 282px;
    width: 1074px;
    margin-bottom: 37px;
    border-radius: 7px;
  }

  .selected-item-title {
    position: absolute;
    bottom: 75px;
    left: 100px;
    color: white;
    font-size: 27px;
    font-weight: 400;
    font-family: 'Segoe UI', sans-serif;
  }

  .scrolling-rows {
    overflow-y: auto;
    overflow-x: hidden;
    flex-shrink: 1;
    flex-grow: 1;
  }

  /* ─── Content Row ──────────────────────────────────────── */

  .content-row {
    margin-bottom: 37px;
  }

  .row-title {
    color: white;
    margin-bottom: 22px;
    font-size: 27px;
    font-weight: 700;
    font-family: 'Segoe UI', sans-serif;
    padding-left: 60px;
  }

  .scrolling-wrapper {
    overflow-x: auto;
    overflow-y: hidden;
    flex-shrink: 1;
    flex-grow: 1;
    padding-left: 60px;
  }

  .scrolling-content {
    display: flex;
    flex-direction: row;
  }

  /* ─── Asset ────────────────────────────────────────────── */

  .asset-wrapper {
    margin-right: 22px;
    display: flex;
    flex-direction: column;
  }

  .asset-box {
    height: 127px;
    border: 0 solid white;
    box-sizing: border-box;
    border-radius: 7px;
  }

  .asset-box.focused {
    border-width: 6px;
  }

  .asset-title {
    color: white;
    margin-top: 10px;
    font-family: 'Segoe UI', sans-serif;
    font-size: 24px;
    font-weight: 400;
  }

  /* ─── Progress Bar ─────────────────────────────────────── */

  .progress-wrapper {
    position: absolute;
    bottom: 95px;
    right: 100px;
    width: 540px;
    height: 24px;
    background-color: gray;
    border-radius: 21px;
    border: 0 solid white;
    box-sizing: border-box;
  }

  .progress-wrapper.focused {
    border-width: 6px;
  }

  .progress-bar {
    height: 100%;
    background-color: dodgerblue;
    border-radius: 21px;
  }

  .progress-bar.focused {
    background-color: deepskyblue;
  }
</style>
